package exceptionhandeling;

public class ExceptionHandelingExample1
{
   static void check() throws ArithmeticException
   {
	   System.out.println("inside check function");
	   throw new ArithmeticException("GOOGLE");
   }
   public static void main(String args[])
   {
	   try
	   {
		   check();
		   
	   }
	   catch(ArithmeticException e)
	   {
		   System.out.println("caught "+e);
	   }
	
   }
}
